#! /usr/bin/env python
from __future__ import print_function
from builtins import str

import subprocess
import sys


def get_status_output(*args, **kwargs):
    p = subprocess.Popen(*args, **kwargs)
    stdout, stderr = p.communicate()
    return p.returncode, stdout, stderr


def system(cmd):
    print("====> Running", cmd)
    p = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True, bufsize=1
    )
    for line in iter(p.stdout.readline, b""):
        print(line)

    st = p.wait()
    if st != 0:
        sys.exit("Error: command %r failed" % cmd)
    print()


def main():
    st, tags, _ = get_status_output(
        "git tag", stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True
    )
    assert st == 0, "failed to get tags"
    tags = set(tags.split())
    import setup

    version = setup.get_version()

    assert version not in tags, "already have tagged %s" % version

    st, description, _ = get_status_output(
        "git describe --all --dirty", stdout=subprocess.PIPE, shell=True
    )
    assert st == 0
    dirty = "-dirty" in str(description)
    if dirty:
        print("working directory is dirty")

    # st, tag = commands.getstatusoutput("git describe --tags --exact-match --dirty")
    # tag = tag.strip()
    # assert st == 0, "revision not tagged"
    # import setup
    # assert setup.get_version() == tag, "version mismatch: %s != %s" % (setup.get_version(), tag)

    system("tox")
    system("%s setup.py -q sdist" % sys.executable)
    if not dirty:
        system("%s setup.py register" % sys.executable)
        system("%s setup.py -q sdist upload" % sys.executable)
        system("git tag %s" % version)
    else:
        print("WARNING: build was dirty. did not upload or tag a release")
        sys.exit(1)


if __name__ == "__main__":
    main()
